package Quiz;

public enum Kategorie {

// Enum - spezieller Datentyp der feste Werte definiert
	
	RESSOURCEN_DER_ERDE,
	PLASTIK_UND_MUELL,
	ERNAEHRUNG_UND_LEBENSMITTELVERSCHWENDUNG,
	KLIMAWANDEL_UND_ENERGIE,
	TIERE_UND_ARTENVIELFALT,
	WAS_KANN_ICH_TUN
}

